### ISSUE TITLE
Permission for money

### ISSUE THREAD

**Issue by jakepavek** [ImagicTheCat/vRP#172]
Add permission for money so we can make a paycheck script?

_Sent from my Samsung SM-G920V using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ImagicTheCat** [comment]
Please don't open issues when I already answered here and on the forum the same things over and over. There are no jobs in vRP, only tools to make them, so there are no paychecks. You can easily make a vrp extension handling generic paychecks, lot of people will find it useful, but I will not do it myself, because I don't believe in the value of paychecks in a RP game.

**Comment by jakepavek** [comment]
Just needs a permission added to money.

**Comment by ImagicTheCat** [comment]
What are you talking about ?

**Comment by jakepavek** [comment]
Like vRP.givemoney (userid,blah, permission="police.paycheck")

**Comment by ImagicTheCat** [comment]
Just use vRP.hasPermission ?
