### ISSUE TITLE
Dirty Money HUD

### ISSUE THREAD

**Issue by hadesfx8** [ImagicTheCat/vRP#174]
Hi :)
Can someone explain to me how to display dirty money in the HUD?
I tried several things but I can not do it, the same for the display of the group.

Thx in advance.

**Comment by T3rg0s** [comment]
Hello, try to use this function= **vRP.getInventoryItemAmount(user_id,idname)**
for retrieve number of a specific item in player's inventory.

**Comment by ImagicTheCat** [comment]
The issue section is not for help, even if you have now your answer. I will now ban people not reading the issues guidelines before submitting issues.

**Comment by NeFShARk** [comment]
@ImagicTheCat I think that you should create a issue, feature, PR and etc template to people to use it and ban anyone that doesn't use it because he\she did not take any time to read thinks around here!

Examples of what i mean:

https://github.com/AsYetUntitled/Framework/blob/master/.github/ISSUE_TEMPLATE.md
https://github.com/AsYetUntitled/Framework/blob/master/.github/PULL_REQUEST_TEMPLATE.md
https://github.com/AsYetUntitled/Framework/blob/master/.github/CONTRIBUTING.md

I think that something like this /\ could help you understand what people are exactly reporting, asking for\suggesting, pull requesting and etc.

Thank you for this amazing framework, it's a lot more organized!

**Comment by ImagicTheCat** [comment]
Thanks for the tip, if the project start to have a lot of issues I will probably do something like that.
