### ISSUE TITLE
[Feature] More than one vehicle outside of garages

### ISSUE THREAD

**Issue by ARL64** [ImagicTheCat/vRP#201]
Because that's very annoying to only have one vehicle outside, could be like 2-3 or in a config file.

**Comment by HIsShadowONE** [comment]
i too was wondering if we can change this limit , sometimes you want to borrow someone a car or take a car to a heli/boat etc and let someone drive while you fly and the limit prevents things like this.

**Comment by ImagicTheCat** [comment]
You can have someone drive while you fly, because you can have one vehicle of each type. I don't plane to implement multiple vehicles per type, because it breaks how everything work currently and because I don't see the benefit, adding to this that vehicles have sync issues causing the system to not recognize them.

**Comment by HIsShadowONE** [comment]
lets say im roleplaying a husband and i have a wife , and i own two cars and we go to work at the same time , she cant use the other car because i own it shel have to own her own .

lets say i roleplay as a big time criminal with a crew and were setting up a job and i own all the cars, and i want to avoid having either known cars owned by the criminals or have all cars trace back to me if we get caught, i cant setup my crew with cars to use in a robbery theyl all have to own their own car ,

the roleplay reasons go on and on .... BUT if its a code limitation i understand just trying to give you my logical reasons why i was asking for it so you better understand the RP possibilities to the system and how those options are limited. i dont want to break anything but violating what the code cant handle though, if this is something that cant be changed without that happening, anyways thanks for your response  :D

**Comment by ImagicTheCat** [comment]
I don't understand what you are saying ? You also want to be able to give owner permission to people ? It's even more complicated than the first request.

**Comment by HIsShadowONE** [comment]
no , i want to be able to borrow my other cars i own to other people (while having my own car out) so they dont have to own them.  for example like to be able to have a mafia boss setup his crew with cars for jobs to have certain roleplay aspects. like scenes out of fast and furious.

**Comment by ImagicTheCat** [comment]
Create a new resource with a new garage type, inspired by the current basic_garage, because I don't plan to do it. Borrowing car is not really interesting since you can't use the vehicles functions.

**Comment by HIsShadowONE** [comment]
oh ya i guess thats a simple solution that will work could just make them car1 car2 and have a separate garage for each so you can remove diff cars, thanks :D (this also shows a possible way to setup personal home garages too) although il wait for that to be added to the base as i see you have that on to do list, thanks again as always @ImagicTheCat :)
