### ISSUE TITLE
[BUG] Basic sell garage feature

### ISSUE THREAD

**Issue by T3rg0s** [ImagicTheCat/vRP#216]
Hello @ImagicTheCat, there is a problem with this function, when player has vehicle out, he can sell the vehicle and keep it (vehicle won't despawn).

Thanks in advance for your amazing dev!

**Comment by ImagicTheCat** [comment]
Yes I know, it's not so bad, unless your sell factor is less damageable than the rent factor.

**Comment by T3rg0s** [comment]
At the beginning of your framework, I modified the garage function for to implement the "In/Out" state in BDD. Are you interested ?

**Comment by ImagicTheCat** [comment]
You respawn the vehicles at their old out position ? If yes, it's something that I had in mind, but I don't know yet how to do it without breaking everything when your vehicle respawn.

**Comment by T3rg0s** [comment]
Nop, when I spawn vehicle, I set state to "Out" in BDD.
When I despawn it, I set state to "In". And when player leave server, it reset state directly to "In".
Like this:
```
    local state = "in"
    q_set_vehgroup_state:bind("@user_id",user_id)
    q_set_vehgroup_state:bind("@vehicle",veh_type)
    q_set_vehgroup_state:bind("@state",state)
    q_set_vehgroup_state:execute()
```

**Comment by ImagicTheCat** [comment]
Oh I see, I'm not interested, at this point vehicles only exist while in game.

**Comment by T3rg0s** [comment]
Yes, but if player disconnect when another player is already in the car, we have a problem :D

**Comment by ImagicTheCat** [comment]
The engine manage the car spawn/despawn, I have even saw issues with vehicles being lost (the engine respawn it, so the id doesn't match in basic garage) if you go too far away or if you teleport. Fixing a car can not work also because of the synchronization between players, causing the car to rollback to a not fixed state. That's the problem of client-side games trying to synchronize themselves, no idea how to smooth this.

**Comment by T3rg0s** [comment]
Really strange, I made a lot of tests according that you describe, and I didn't noticed any losing vehicle.
