### ISSUE TITLE
[Feature] Same item transformer in multiple places

### ISSUE THREAD

**Issue by BobbyLinny** [ImagicTheCat/vRP#283]
Make item transformers be able to have multiple permanent locations as at moment one transformer is attached to one location.

**Comment by HIsShadowONE** [comment]
this already works look at the very first example in item transformers ....

**Comment by BobbyLinny** [comment]
No there is only one x,y,z line per transformer at the moment...

**Comment by Sighmir** [comment]
just make a transformer like this on the item_trasnformer.cfg
`local warehouses = {
  {-1111.2841796875,4937.4052734375,218.386306762695},
  {1539.01794433594,1704.29174804688,109.659622192383},
  {981.412841796875,-1805.70349121094,35.4845695495605}
}
for k,v in pairs(warehouses) do
  local warehouse = {
    name="Gun Warehouse", -- menu name
    permissions = {"build.gun"}, -- you can add permissions
    r=0,g=200,b=0, -- color
    max_units=10,
    units_per_minute=1,
    x=v[1],y=v[2],z=v[3], -- pos
    radius=5.0, height=1.5, -- area
    recipes = {
    }
  }
  table.insert(cfg.item_transformers, warehouse)
end`

**Comment by HIsShadowONE** [comment]
its literally in the first file did you even look at how it is done ....
cfg.item_transformers = {
  -- example of harvest item transformer
  {
    name="Water bottles/tacos tree", -- menu name
    -- permissions = {"harvest.water_bottle_tacos"}, -- you can add permissions
    r=0,g=125,b=255, -- color
    max_units=20,
    units_per_minute=10,
    x=1861,y=3680.5,z=33.26, -- pos
    radius=5, height=1.5, -- area
    recipes = {
      ["Harvest water"] = { -- action name
        description="Harvest some water bottles.", -- action description
        in_money=0, -- money taken per unit
        out_money=0, -- money earned per unit
        reagents={}, -- items taken per unit
        products={ -- items given per unit
          ["water"] = 1
        }
      },
      ["Harvest tacos"] = { -- action name
        description="Harvest some tacos.", -- action description
        in_money=0, -- money taken per unit
        out_money=0, -- money earned per unit
        reagents={}, -- items taken per unit
        products={ -- items given per unit
          ["tacos"] = 1
        }
      }
    }
    --, onstart = function(player,recipe) end, -- optional start callback
    -- onstep = function(player,recipe) end, -- optional step callback
    -- onstop = function(player,recipe) end -- optional stop callback
  },
 as you can see it provided two diff items to be transformed/harvested at the exact same location as an example of how to do exactly what your asking ....

**Comment by BobbyLinny** [comment]
Did you even read my suggestion, you can only give that transformer one location not multiple which is my suggestion.

**Comment by HIsShadowONE** [comment]
oh i see i was confused by the second part of your post as to one transformer locked to one location (thought you wanted multiple transformers at one location), and your response didnt clarify that for me it only enforced what i was saying , now i see clearly , you didnt look at the end of the file not the beginning and your question i still already answered and been in the file since day one ... same result just confused what you wanted to do ... (this however needs to use hidden transformers but could likely be adapted to non hidden if this is your wish)

-- define transformers randomly placed on the map
cfg.hidden_transformers = {
  ["weed field"] = {
    def = {
      name="Weed field", -- menu name
      -- permissions = {"harvest.weed"}, -- you can add permissions
      r=0,g=200,b=0, -- color
      max_units=30,
      units_per_minute=1,
      x=0,y=0,z=0, -- pos
      radius=5, height=1.5, -- area
      recipes = {
        ["Harvest"] = { -- action name
          description="Harvest some weed.", -- action description
          in_money=0, -- money taken per unit
          out_money=0, -- money earned per unit
          reagents={}, -- items taken per unit
          products={ -- items given per unit
            ["weed"] = 1
          }
        }
      }
    },
    positions = {
      {1873.36901855469,3658.46215820313,33.8029747009277},
      {1856.33776855469,3635.12109375,34.1897926330566},
      {1830.75390625,3621.44140625,33.8487205505371}
    }
  }

**Comment by BobbyLinny** [comment]
That's not what I mean... that example randomly places the transformer on ONE of the locations, what I'm requesting is that a single transformer can be located at multiple locations all the time.

**Comment by ImagicTheCat** [comment]
Item transformers are universal structures used by many functions, the config file is only one of the way to add them, so it's not good to adjust properties for ease of configuration. As you can see, the multiple positions of hidden transformers are outside the item transformers structures.

Since all config files are in Lua (and executed), the best way to batch is to algorithmic-ally define them as shown by @Sighmir .
