### ISSUE TITLE
Index Out of range problem

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#3]
Hello,
again thank's a lot for your amazing job... I was working on a vehicule shop just before your commit, and your garage system its better  :D.
Unfortunately, the "Owned/Buy" system doesn't work.
When you bought a car, and you try to go to "Owned Menu"; there is an "Index out of range" error (basic_garage.lua ligne 67 and 105).
I think its related to the zero index with toTable() but I can't fix it...
Thank's in advance for your answer :).
 (and for the No police flag, will be better to add the unwanted loop check, no?)

**Comment by ImagicTheCat** [comment]
I have no issue on a different server, did you copy the new config files and check the differences ?
(for the police flag, if I can avoid a loop, it's better, needs some testing)

**Comment by 3rg00** [comment]
Thanks for your update, but I have same problem.
Really strange.

**Comment by 3rg00** [comment]
![image](https://cloud.githubusercontent.com/assets/140156/25649474/18c9ad90-2fd6-11e7-99fd-7c62034eda4c.png)
This is the error message

**Comment by 3rg00** [comment]
I tried to install on a new system (w10/mariaDB), and I have same error occurs...

**Comment by ImagicTheCat** [comment]
Add this after line 102 of lib/MySQL/MySQL.lua
`lua
print(i.." -> "..self:GetName(i).." = "..self:GetValue(i))
`
And show me the ouput.

**Comment by 3rg00** [comment]
Here is the output:

**Comment by 3rg00** [comment]
The output:
![image](https://cloud.githubusercontent.com/assets/140156/25655389/f4708508-2ff4-11e7-8183-39cf80192939.png)

**Comment by ImagicTheCat** [comment]
That's strange, NeoLua seems to fail to insert the object to the table, something may have corrupt NeoLua somewhere (I have experienced things like this before, like the `"" ~= nil` in playerConnecting). 

Try to replace the toTable function by this : 
```lua
function Result:toTable() -- auto close the result
  local r = {}

  local i = 1
  while self:fetch() do
    r[i] = self:getRow()
    i = i+1
  end

  self:close()

  return r
end
```

**Comment by 3rg00** [comment]
Yeah now its working correctly !

Did you think that the corruption is related to another  Fivem ressources ? (I only have bases ressources and your vrp framework).

Anyway, thank's a lot for your support !

Really need to participate in your project, for now only basic improvments (money HUD, lock car, etc..), if you want to ?

**Comment by ImagicTheCat** [comment]
I don't know, NeoLua/FiveM is very strange sometimes, maybe vRP do something wrong somewhere, maybe not.

All contributions are welcomed, but I will always inspect/modify the changes to keep the consistency of vRP, and there are things I have already planned to do, the money display use a progress bar right now, I will change that. But nothing stop you from creating a custom HUD, I just need to add some events.

For locking the car, you can add choices to the main menu, in fact you don't even need to change vRP for that but if the functionalities are very useful and generic, why not.

Right now there are things to do that I can't right now, if you want to because it's painful (I use lambda menu to display the player coordinates):
- setting decent RP positions to all shops in the default config files (market inside not outside, etc)
- adding most vehicles and weapons with coherent prices

**Comment by 3rg00** [comment]
Nice, I will start in first with it :).
thanks a lot ! I will do a few pull requests in the future :).

**Comment by ImagicTheCat** [comment]
No problem, I lock the issue to let people find a solution if they have the same problem.
