### ISSUE TITLE
Idea for better RP phone using

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#34]
Again, thank's a lot for your time passed on this project, its really amazing !

Is it possible to improve the phone system for to allow player only use it if they bought a phone item ?
In fact, is it possible to allow some "interactions" based on items requirements ?

Thank's in advance :).

**Comment by Zuqaa** [comment]
Yes Good Idea ! Add a items phone in Market and if the player have bought a phone then the phone is fonctionnal :) And make same for the minimap u set the minimap on false ( i have the code if you want) and if the player have bought a gps then he see the minimap ;)

**Comment by 3rg00** [comment]
@ImagicTheCat, do you have you any mail/plateform for to contact you directly, for not pollute this project :)

**Comment by Zuqaa** [comment]
3rg00 if its my fault i delete my message if you want :(

**Comment by 3rg00** [comment]
lol, no, its for another things.

**Comment by Zuqaa** [comment]
Ah ok ^^

@ImagicTheCat The code for desactivate the map:

```lua
Citizen.CreateThread(function()
        while true do
		Wait(1)
		if not displayRadar then
			DisplayRadar(false)
		end
	end
end)
```

**Comment by ImagicTheCat** [comment]
Hm this one is tricky, to ensure stability of vRP I can't give this much control over actions as checking item or accepting use of the phone, but I can add a phone permission. This way you can add an item "Packed Phone", that when used will auto-delete itself and give the phone group to the player. If he respawn, you can just remove the phone group.
For the radar, you can create another resource to check if the player has the item you created, using the API, and show/hide the map at a specific interval. Or even add an item action "Enable/disable map", which is easier.

I will not make this a core feature because you spawn with an adult character, with clothes, in a city, so it's legit to spawn with a phone after all. But it's cool to make it possible.

You can contact me on the FiveM forum using private message (https://forum.fivem.net/u/Imagic/).

**Comment by 3rg00** [comment]
Yep it's not a bad idea finally... The group permission is a good way for to restrict any player for specific reason (for example we player get jailed). If you can show us an example of interaction with item, will be really nice :).

**Comment by ImagicTheCat** [comment]
It's exactly the same as drinking a bottle, you just use vRP.addUserGroup instead.

**Comment by 3rg00** [comment]
Ups sorry for this stupid question... I will check this, thanks a lot :D, and pull if it can serve!

**Comment by ImagicTheCat** [comment]
No problem, the API is here to give potential, try to play with it (you can define your phone item in cfg/items.lua to avoid some of the callback hell). 
The phone permission is added, you can try it now.

**Comment by 3rg00** [comment]
I tried, it works perfectly ! I have just a little problem for to set restriction with identity, for hide phone number too :). Thanks a lot !

**Comment by ImagicTheCat** [comment]
Hiding phone number ? Why ? For the business ?

**Comment by Zuqaa** [comment]
Thx ImagicTheCat, how to make for set a limit of items ex: i can only bough a 1 phone

**Comment by 3rg00** [comment]
Nop, for RP, because if player don't buy phone, this is normal that he can't show his number.

        if vRP.hasPermission(user_id, "player.phone") then
          local content = lang.cityhall.menu.info({htmlEntities.encode(identity.name),htmlEntities.encode(identity.firstname),identity.age,identity.registration,identity.phone})
          local choices = {}
          choices[lang.cityhall.menu.title()] = {function()end, content}
          vRP.buildMainMenu(player,choices)
        else
          local content = lang.cityhall.menu.info({htmlEntities.encode(identity.name),htmlEntities.encode(identity.firstname),identity.age,identity.registration,"No Phone number"})
          local choices = {}
          choices[lang.cityhall.menu.title()] = {function()end, content}
          vRP.buildMainMenu(player,choices)
        end

**Comment by ImagicTheCat** [comment]
Hm, will look into this, but I think this is too much problems since it needs change in identity, business, and also the sms history.
See the phone number as a pre-reserved number, since it doesn't change if you buy a new phone, I will add the permission check before sending the SMS, but I don't think I will hide the number.

**Comment by 3rg00** [comment]
Okay, I think it's better to change the "ingame introduction" for players, for example all new players has a phone number but they must buy a phone in first for using it :).
