### ISSUE TITLE
[BUG] deferrals.done

### ISSUE THREAD

**Issue by SnaiCrys** [ImagicTheCat/vRP#342]
After da17c78 players who not whitlisted see `unknown client` instead of `"[vRP] Not whitelisted (user_id = "..user_id..").")`

![b5108-clip-15kb](https://user-images.githubusercontent.com/4284827/30031379-c2b65bf8-9199-11e7-9987-d308f42ca9fe.jpg)

**Comment by DjRicko** [comment]
This seems to be related to deferrals way of connecting and the client not properly showing the reason it gets dropped/kicked when rejected by deferrals.done("message").
Can't seem to find an error in the implementation in vRP compared to the one in FiveM documentation, so wondering if its actually a FiveM bug?

**Comment by Anark-Link** [comment]
@DjRicko not a friend, this problem is something related to withelist, the client is not receiving a message from the witheliste correctly, informing an unknown client, invention of informing a message from the withelist.
For example, ex: a player looking for one more time without a checked witheliste, instead of receiving a message from the list withe: 

deferrals.done ("[vRP] Not listed on the white list (user_id =" ..user_id .. ").")

He is "unknown customer" in the message.

**Comment by ImagicTheCat** [comment]
Sometimes it says "unknown client" for me. On a localhost server I tested more than 15 consecutive connections with the correct output. Maybe the server is closing the TCP socket too soon, preventing the message to be sent to the client.

**Comment by CChampa** [comment]
Has anyone managed to solve it?

**Comment by luisflorido** [comment]
I have the same bug.

**Comment by ImagicTheCat** [comment]
News ?
