### ISSUE TITLE
[vRP] Players losing money when reloggging etc.

### ISSUE THREAD

**Issue by jskov9850** [ImagicTheCat/vRP#367]
Ever since my server started and I installed vRP, players has been losing their money. I have switched host twice with a new database each time but player still lose their money. I was told that this was an issue with vRP and there was a fix for it. It has been getting worse and worse I think (or maybe just randomly)

Can someone help me? There is no errors in the console and the database is working fine. I am using MySQL with phpMyAdmin

We usually have around 20-32 players online at once and we are using vRP (FXServer 3.5?)

I saw a "more robuste money fix" but I already seem to have that code in my money.lua.

The code can be found at a hastebin here: https://hastebin.com/umuzexasam.lua

I couldnt seem to make the "insert code" function work.

**Comment by ImagicTheCat** [comment]
It is problematic that people are doing their own fixes instead of working on the base project by discussing about it. I am not the most suited to solve this issue because I can't reproduce it (I don't have a server with a minimal amount to people to trigger the bug). It could be the save loop failing or putting wrong values before saving. I will investigate the code, but I can't investigate around the issue itself, if they have a fix, they probably did, having their results here would be useful.

**Comment by ImagicTheCat** [comment]
obsolete
