### ISSUE TITLE
[feature request] door locks

### ISSUE THREAD

**Issue by AceDax** [ImagicTheCat/vRP#503]
so members of my community are asking me about being able to lock doors and gates which is something we would like to do for RP reasons. before I attempt to make an extension I would like to see if you are interested in adding such a feature to the base framework since it is a widely popular feature across RP servers.

For reference this is basicly what is being requested by my community however I personally believe there is much room for improvement, such as adding the ability to lock and unlock gates and garage doors. 

https://forum.fivem.net/t/release-doors-control-vrp/82797

the RP possibilities are endless with a feature like this, from locking someone in a jail cell to players owning Michael or Franklins house and having to unlock the door with a key for some added realism.

and like I said I don't mind converting this to be a vRP2 extension but I wanted to see if you were interested in such a feature being in the base due to its popularity among RP servers

**Comment by ImagicTheCat** [comment]
vRP already has a lot of stuff into it, but it never aimed to be a collection of scripts. I mostly worked on those extra modules because it was interesting and to show what can be done. Now with the vRP 2 release I will move on to other projects; I will maintain vRP and probably stop adding stuff. 

So go ahead, now with vRP 2 there is no drawback to make extensions (all vRP core modules are extensions).
