### ISSUE TITLE
Revive and Heal

### ISSUE THREAD

**Issue by bradxy** [ImagicTheCat/vRP#551]
There is a issue where revive and healing with pills works sometimes and suddenly stops working at random, I testing on a generic vrp server (stock) with no other resources loaded and had the same problem...

**Comment by zbadrabbit** [comment]
I can also confirm that there is an intermittent issue with revive on our server. Players have reported a 1 in 5 chance to revive someone and the players that do not revive receive full health but remain in coma state. If they logout/login then they spawn with all their items/money but return to City Hall.

**Comment by AceDax** [comment]
Confirmed same issue with my server, my community members first started reporting the issue on July 1st, I believe one of the fiveM update around that time change something and this is a unexpected side effect of that change. perhaps this little bit of info can help track down the issue.

**Comment by zbadrabbit** [comment]
Using a temporary workaround until I can look at this closer, I implemented
`if self.in_coma then -- and PlayerState.state_ready then -- get out of coma state`
which can at least keep a bandaid on the situation.

**Comment by AceDax** [comment]
anyone have any luck here yet with resolving this issue?

**Comment by ImagicTheCat** [comment]
vRP version ?

**Comment by bradxy** [comment]
Just confirmed this is still a issue, and on current version of vRP. 

Removing "and PlayerState.state_ready" from line 103 in client/survival.lua allows them to be revived or respawn, but when re logging it will spawn u at city hall...

**Comment by ImagicTheCat** [comment]
_discord echo_
> Okay, it seems that the issue is a side-effect of the coma hack.
Coma feature is not something really stable in the first place, sometimes you may see a notification about being dead, when still on the ground.
The survival module try to keep the player alive by setting the life to the threshold every game tick, which seems to work well, but death events are still fired.
The player state module is listening to the death event to mark the player as "not ready" for other purposes, but the player is not really dead.
This is much worse than just not being revived, the phone/inventory may be lost because of this.
vRP event listeners are in a map, so the iteration is not in a specified order. When the PlayerState module event fires first, it probably breaks the Survival module behavior.

**Comment by ImagicTheCat** [comment]
try https://github.com/ImagicTheCat/vRP/commit/c33ed0d0a6228e4438fa53cdf90128379844380d

**Comment by bradxy** [comment]
All working now!
