### ISSUE TITLE
Markers/Blips customization

### ISSUE THREAD

**Issue by 3rg00** [ImagicTheCat/vRP#56]
Hello @ImagicTheCat, just a little question, is it possible to customize a particular marker/blip for hidden to players that don't have a permission? I found a solution but with override the markers/blips generation in modules code, so it's really a bad idea to do this...

**Comment by ImagicTheCat** [comment]
What kind of blip ? Related to a menu ? You want the menu permission to also hide the blip ?

**Comment by 3rg00** [comment]
For example, I set an Police Armory, and I want to complete hide the blip and the marker, for more RP.

**Comment by ImagicTheCat** [comment]
It's not really possible because groups are dynamic (so are permissions), but blips are not. Trying to hide/show blips in function of permissions is complicated and will lead to "blip leaks", or worse, missing blips. What you can do is using the spawn/leave callbacks of your group to set and remove the blips manually. So I just need to add something to hide blips for everyone, by setting the blipid to -1 for example. 

The markers shouldn't be a problem, I like that everyone can see in 3d space the interactions points, but you can set the alpha of the marker to 0 and then add a new marker with the callbacks. 

Shops are persistent things, they don't have been built to be visible or not, as a locked building, you can't enter the building, but it is visible. But I understand the problem of "too many blips on the map".

**Comment by 3rg00** [comment]
Hmm ok, thanks. Do you have any examples for using theses tips?

**Comment by ImagicTheCat** [comment]
Just use a named marker (easier to remove), in the group callbacks (onspawn, onleave). You have direct access to vRP (no needs of proxy), and vRPclient (which is a tunnel to the client). So use vRPclient.setNamedBlip, vRPclient.removeNamedBlip, vRPclient.setNamedMarker, vRPclient.removeNamedMarker, using the name you want (it's good to use a prefix like "my:" to prevent name collisions).

**Comment by 3rg00** [comment]
Hmm, okay, I tried to use _config = {onspawn = function(player) vRPclient.setNamedBlip("Armory", 452.164, -979.959, 30.6896,110,76,"Armory") end}, Im not sure this is correct because it doesn't work...

**Comment by ImagicTheCat** [comment]
It's the tunnel call server-side, so you missed the player/sourceand the "{}" around the arguments.
```lua
vRPclient.setNamedBlip(player, {"your_prefix:armory", 452.164, -979.959, 30.6896,110,76,"Armory"})
```

**Comment by 3rg00** [comment]
I missed the concept, sorry ^^. Now it works perfectly, I can make complex marker/blips show based on permissions, its perfect, thank's a lot !

**Comment by 3rg00** [comment]
Just one more question about the clientside, is it possible to use removeNamedBlip() on Blip that initiated throught the basic_gunshop or basic_garage ? I tried with the direct name but it appear don't work.

**Comment by ImagicTheCat** [comment]
You can only use removeNamedBlip for ... named blips. They are created with addBlip.

**Comment by 3rg00** [comment]
Hmm ^^ noob question, thanks.

**Comment by 3rg00** [comment]
So, its not possible to hide markers from player (police garage and police armory) that use garage and gunshop concept. I think it will be better to use Loadouts and simple spawn vehicles for Police job, no ?

**Comment by ImagicTheCat** [comment]
I need to add an optional marker customization property, available soon.

**Comment by 3rg00** [comment]
Thanks @ImagicTheCat  :)
