### ISSUE TITLE
Can't reload my custom vRP scripts

### ISSUE THREAD

**Issue by DaniloMaglia** [ImagicTheCat/vRP#599]
Every time i try to reload my vRP scripts the server load the script on top of the other creating multiple instances of the same script. This is a problem because the method are called more than once making the same thing happen multiple time.

**Comment by zThundy** [comment]
the problem could be that you are registring mysql commands multiple times when the script get restarted. try to create a script with all the mysql commands inside (ore use mysql async like you should do)

**Comment by JeckBiagio** [comment]
Isn't a mysql problem, just all the functions called repeats 2 times, like if there are 2 modules of the same script

**Comment by ImagicTheCat** [comment]
Reloading is not possible for many reasons (FiveM hooks, vRP design, extensions quality, etc.).

**Comment by JeckBiagio** [comment]
There is a method maybe to unload the module and replace it with the refreshed one? Because with the old vrp you can reload for the fact that you get the main vRP instance and take methods from it

**Comment by ImagicTheCat** [comment]
It never has been the case, it's undefined behavior.

> Imagic 30/04/2019 (discord)
 This a design problem, fixing that error or changing the name will not solve it.
Resources can depend on each others (extensions depend on vRP by design), so part of the state of a specific extension can exist in vRP or any other extensions, so they need to be reloaded too.
If you reload vRP, then you need to reload all the extensions.
A better way would be to let extensions define how to unload stuff when they are unloaded.
But a lot of stuff is not done with this in mind and it will not solve all the problems (some dependencies).
Also, I see no guarantee about FiveM on resource stop/start and earliest events (connections, etc).
Another issue is, for example, if the client resource send a spawn event to the server resource, then their state may be correlated, if the server resource is restarted, what about the client resource ?
I mean, I would be happy to implement such stuff, but in a context like FiveM which lacks of rigor IMHO that can't be done properly.
```
