### ISSUE TITLE
Question with GetPlayerPed in vRP

### ISSUE THREAD

**Issue by Zuqaa** [ImagicTheCat/vRP#71]
I have a question, Is there a variant of "GetPlayerPed" in vRP?

**Comment by ImagicTheCat** [comment]
I'm going to be more strict about issues from now, I don't want the issues to become a way to chat with me. All you "need" to know is in the README, I will maybe break it in multiple files later, because it seems that people are scared of it.
Issues are for features or bug reports, this is not a support section, this is not a chat section. 
vRP is not released yet, if you use it, you deal with its beta state. When I will create a topic on the FiveM forum, then you will be able to ask such things, and I hope I will not be the only one to respond to you.

**Comment by Zuqaa** [comment]
sorry to have disturbed you :(
good luck or the next..
